export const metadata = {
  title: "Terms of Use | Yoryantra",

  description:
    "Read the terms and conditions for using Yoryantra tools and services.",
};

export default function TermsPage() {
  return (
    <div className="max-w-4xl mx-auto px-6 py-20">

      <h1 className="text-4xl font-bold text-gray-900 mb-8">
        Terms of Use
      </h1>

      <div className="space-y-6 text-gray-700 leading-8">

        <p>
          By accessing and using Yoryantra, you agree to use the platform
          responsibly and only for lawful purposes.
        </p>

        <p>
          All tools and utilities are provided “as is” without warranties
          of any kind. While we aim to provide accurate and reliable tools,
          Yoryantra does not guarantee uninterrupted availability,
          completeness, or error-free operation.
        </p>

        <p>
          Users are responsible for verifying outputs generated by the
          tools before relying on them for professional, technical,
          financial, or legal purposes.
        </p>

        <p>
          Yoryantra may update, modify, improve, or remove features,
          tools, or content at any time without prior notice.
        </p>

        <p>
          We are not liable for any direct, indirect, incidental,
          or consequential loss or damage resulting from the use
          of this website or its tools.
        </p>

        <p>
          Continued use of Yoryantra indicates acceptance of these
          terms and any future updates made to this page.
        </p>

      </div>

    </div>
  );
}